// <auto-generated />
using System;
using HTQL_DichVuYTeGiaDinh.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HTQL_DichVuYTeGiaDinh.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240927151507_AddCompositeKeyToDonGia")]
    partial class AddCompositeKeyToDonGia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.BacSi", b =>
                {
                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("DIA_CHI");

                    b.Property<string>("DiaChiEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DIA_CHI_EMAIL");

                    b.Property<short>("GioiTinh")
                        .HasColumnType("smallint")
                        .HasColumnName("GIOI_TINH");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("HINH_ANH");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HO_TEN");

                    b.Property<int>("MaChuyenKhoa")
                        .HasColumnType("int")
                        .HasColumnName("MA_CHUYEN_KHOA");

                    b.Property<int?>("MaQuyen")
                        .HasColumnType("int")
                        .HasColumnName("MA_QUYEN");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MAT_KHAU")
                        .IsFixedLength();

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_SINH");

                    b.Property<string>("SoCccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("SO_CCCD")
                        .IsFixedLength();

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SO_DIEN_THOAI")
                        .IsFixedLength();

                    b.Property<string>("TrinhDoHocVan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRINH_DO_HOC_VAN");

                    b.HasKey("MaTk");

                    b.HasIndex(new[] { "MaChuyenKhoa" }, "THUOC_CHUYEN_KHOA_FK");

                    b.ToTable("BAC_SI", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.BinhLuan", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_BINH_LUAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"), 1L, 1);

                    b.Property<decimal>("DiemDanhGia")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("DIEM_DANH_GIA");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnName("MA_DICH_VU");

                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<string>("NoiDungBinhLuan")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("NOI_DUNG_BINH_LUAN");

                    b.Property<DateTime>("ThoiDiemBinhLuan")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("THOI_DIEM_BINH_LUAN");

                    b.HasKey("MaBinhLuan");

                    b.HasIndex(new[] { "MaBinhLuan" }, "BINH_LUAN_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "MaDichVu" }, "CO_BINH_LUAN_FK");

                    b.HasIndex(new[] { "MaTk" }, "VIET_BINH_LUAN_FK");

                    b.ToTable("BINH_LUAN", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChiTietDonThuoc", b =>
                {
                    b.Property<int>("MaDonThuoc")
                        .HasColumnType("int")
                        .HasColumnName("MA_DON_THUOC");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int")
                        .HasColumnName("MA_THUOC");

                    b.Property<string>("HuongDanSuDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HUONG_DAN_SU_DUNG");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG");

                    b.HasKey("MaDonThuoc", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.ToTable("CHI_TIET_DON_THUOC", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChiTietKetQuaCanLamSang", b =>
                {
                    b.Property<int>("MaPhuongPhap")
                        .HasColumnType("int")
                        .HasColumnName("MA_PHUONG_PHAP");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int")
                        .HasColumnName("MA_HO_SO");

                    b.Property<string>("HinhAnhKetQua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HINH_ANH_KET_QUA");

                    b.HasKey("MaPhuongPhap", "MaHoSo")
                        .HasName("PK_CHI_TIET_KET_QUA_CAN_LAM_SA");

                    b.HasIndex(new[] { "MaHoSo" }, "CO_CHI_TIET_KET_QUA_FK");

                    b.HasIndex(new[] { "MaPhuongPhap" }, "CUA_PHUONG_PHAP_CAN_LAM_SANG_FK");

                    b.ToTable("CHI_TIET_KET_QUA_CAN_LAM_SANG", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChiTietKhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.HasKey("MaKhuyenMai", "MaDichVu");

                    b.HasIndex("MaDichVu");

                    b.ToTable("CHI_TIET_KHUYEN_MAI", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaThuoc")
                        .HasColumnType("int")
                        .HasColumnName("MA_THUOC");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int")
                        .HasColumnName("MA_PHIEU_NHAP");

                    b.Property<decimal>("DonGiaNhap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DON_GIA_NHAP")
                        .IsFixedLength();

                    b.Property<int>("SoLuongNhap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG_NHAP")
                        .IsFixedLength();

                    b.HasKey("MaThuoc", "MaPhieuNhap");

                    b.HasIndex(new[] { "MaPhieuNhap" }, "NHAP_CHO_PHIEU_FK");

                    b.HasIndex(new[] { "MaThuoc" }, "NHAP_THUOC_FK");

                    b.ToTable("CHI_TIET_PHIEU_NHAP", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChuongTrinhKhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_KHUYEN_MAI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"), 1L, 1);

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MO_TA");

                    b.Property<DateTime>("NgayBatDauKm")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_BAT_DAU_KM");

                    b.Property<DateTime>("NgayKetThucKm")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_KET_THUC_KM");

                    b.Property<float>("PhanTramGiamGia")
                        .HasColumnType("real")
                        .HasColumnName("PHAN_TRAM_GIAM_GIA");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TEN_KHUYEN_MAI");

                    b.HasKey("MaKhuyenMai");

                    b.HasIndex(new[] { "MaKhuyenMai" }, "CHUONG_TRINH_KHUYEN_MAI_PK")
                        .IsUnique();

                    b.ToTable("CHUONG_TRINH_KHUYEN_MAI", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChuyenKhoa", b =>
                {
                    b.Property<int>("MaChuyenKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_CHUYEN_KHOA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyenKhoa"), 1L, 1);

                    b.Property<string>("TenChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TEN_CHUYEN_KHOA");

                    b.HasKey("MaChuyenKhoa");

                    b.HasIndex(new[] { "MaChuyenKhoa" }, "CHUYEN_KHOA_PK")
                        .IsUnique();

                    b.ToTable("CHUYEN_KHOA", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DichVuYTe", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_DICH_VU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"), 1L, 1);

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DON_VI_TINH");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MO_TA");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TEN_DICH_VU");

                    b.HasKey("MaDichVu");

                    b.HasIndex(new[] { "MaDichVu" }, "DICH_VU_Y_TE_PK")
                        .IsUnique();

                    b.ToTable("DICH_VU_Y_TE", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DonGiaDichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnName("MA_DICH_VU")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("ThoiDiem")
                        .HasColumnType("datetime2")
                        .HasColumnName("THOI_DIEM")
                        .HasColumnOrder(1);

                    b.Property<decimal>("DonGiaDv")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DON_GIA_DV");

                    b.HasKey("MaDichVu", "ThoiDiem");

                    b.ToTable("DON_GIA_DICH_VU", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DonGiaThuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .HasColumnType("int")
                        .HasColumnName("MA_THUOC")
                        .HasColumnOrder(0);

                    b.Property<decimal>("DonGiaThuoc1")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DON_GIA_THUOC");

                    b.Property<DateTime>("ThoiDiem")
                        .HasColumnType("datetime2")
                        .HasColumnName("THOI_DIEM")
                        .HasColumnOrder(1);

                    b.HasKey("MaThuoc");

                    b.ToTable("DON_GIA_THUOC", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DonThuoc", b =>
                {
                    b.Property<int>("MaDonThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_DON_THUOC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonThuoc"), 1L, 1);

                    b.Property<string>("GhiChuDonThuoc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GHI_CHU_DON_THUOC");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int")
                        .HasColumnName("MA_HO_SO");

                    b.Property<DateTime>("NgayKeDon")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_KE_DON");

                    b.Property<string>("TrangThaiDonThuoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANG_THAI_DON_THUOC");

                    b.HasKey("MaDonThuoc");

                    b.HasIndex(new[] { "MaHoSo" }, "CO_DON_THUOC_FK");

                    b.HasIndex(new[] { "MaDonThuoc" }, "DON_THUOC_PK")
                        .IsUnique();

                    b.ToTable("DON_THUOC", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DonViTinhThuoc", b =>
                {
                    b.Property<int>("MaDvt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_DVT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDvt"), 1L, 1);

                    b.Property<string>("TenDvt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEN_DVT");

                    b.HasKey("MaDvt");

                    b.HasIndex(new[] { "MaDvt" }, "DON_VI_TINH_THUOC_PK")
                        .IsUnique();

                    b.ToTable("DON_VI_TINH_THUOC", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_HOA_DON");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"), 1L, 1);

                    b.Property<int>("MaLanSuDung")
                        .HasColumnType("int")
                        .HasColumnName("MA_LAN_SU_DUNG");

                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<DateTime>("NgayLapHoaDon")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_LAP_HOA_DON");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TONG_TIEN");

                    b.HasKey("MaHoaDon");

                    b.HasIndex(new[] { "MaLanSuDung" }, "CO_HOA_DON_FK");

                    b.HasIndex(new[] { "MaTk" }, "CO_NVYT_FK");

                    b.HasIndex(new[] { "MaHoaDon" }, "HOA_DON_PK")
                        .IsUnique();

                    b.ToTable("HOA_DON", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.HoGiaDinh", b =>
                {
                    b.Property<int>("MaHgd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_HGD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHgd"), 1L, 1);

                    b.Property<string>("ChuHo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CHU_HO");

                    b.Property<string>("DiaChiHgd")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DIA_CHI_HGD");

                    b.Property<string>("SodienthoaiHgd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SODIENTHOAI_HGD")
                        .IsFixedLength();

                    b.HasKey("MaHgd");

                    b.HasIndex(new[] { "MaHgd" }, "HO_GIA_DINH_PK")
                        .IsUnique();

                    b.ToTable("HO_GIA_DINH", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.HoSoYTe", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_HO_SO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"), 1L, 1);

                    b.Property<int>("BacMaTk")
                        .HasColumnType("int")
                        .HasColumnName("BAC_MA_TK");

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CHAN_DOAN");

                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<DateTime>("NgayKhamBenh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_KHAM_BENH");

                    b.Property<DateTime?>("NgayTaiKham")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_TAI_KHAM");

                    b.Property<string>("ThongTinKhac")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("THONG_TIN_KHAC");

                    b.HasKey("MaHoSo");

                    b.HasIndex(new[] { "MaTk" }, "CO_HO_SO_Y_TE_FK");

                    b.HasIndex(new[] { "BacMaTk" }, "GHI_HO_SO_Y_TE_FK");

                    b.HasIndex(new[] { "MaHoSo" }, "HO_SO_Y_TE_PK")
                        .IsUnique();

                    b.ToTable("HO_SO_Y_TE", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.KhachHang", b =>
                {
                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("DIA_CHI");

                    b.Property<string>("DiaChiEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DIA_CHI_EMAIL");

                    b.Property<short>("GioiTinh")
                        .HasColumnType("smallint")
                        .HasColumnName("GIOI_TINH");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("HINH_ANH");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HO_TEN");

                    b.Property<int>("MaHgd")
                        .HasColumnType("int")
                        .HasColumnName("MA_HGD");

                    b.Property<int?>("MaQuyen")
                        .HasColumnType("int")
                        .HasColumnName("MA_QUYEN");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MAT_KHAU")
                        .IsFixedLength();

                    b.Property<string>("MoiQuanHeVoiChuHo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MOI_QUAN_HE_VOI_CHU_HO");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_SINH");

                    b.Property<string>("SdtNguoiLienHeKhanCap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SDT_NGUOI_LIEN_HE_KHAN_CAP")
                        .IsFixedLength();

                    b.Property<string>("SoCccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("SO_CCCD")
                        .IsFixedLength();

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SO_DIEN_THOAI")
                        .IsFixedLength();

                    b.Property<string>("TenNguoiLienHeKhanCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TEN_NGUOI_LIEN_HE_KHAN_CAP");

                    b.HasKey("MaTk");

                    b.HasIndex(new[] { "MaHgd" }, "THUOC_HGD_FK");

                    b.ToTable("KHACH_HANG", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.NhanVienYTe", b =>
                {
                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("DIA_CHI");

                    b.Property<string>("DiaChiEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DIA_CHI_EMAIL");

                    b.Property<short>("GioiTinh")
                        .HasColumnType("smallint")
                        .HasColumnName("GIOI_TINH");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("HINH_ANH");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HO_TEN");

                    b.Property<int?>("MaQuyen")
                        .HasColumnType("int")
                        .HasColumnName("MA_QUYEN");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MAT_KHAU")
                        .IsFixedLength();

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_SINH");

                    b.Property<string>("SoCccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("SO_CCCD")
                        .IsFixedLength();

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SO_DIEN_THOAI")
                        .IsFixedLength();

                    b.HasKey("MaTk");

                    b.ToTable("NHAN_VIEN_Y_TE", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.PhanCongBacSi", b =>
                {
                    b.Property<int>("MaHgd")
                        .HasColumnType("int")
                        .HasColumnName("MA_HGD");

                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("THOI_GIAN_BAT_DAU");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("THOI_GIAN_KET_THUC");

                    b.HasKey("MaHgd", "MaTk");

                    b.HasIndex(new[] { "MaHgd" }, "CO_BAC_SI_FK");

                    b.HasIndex(new[] { "MaTk" }, "PHAN_CONG_HGD_FK");

                    b.ToTable("PHAN_CONG_BAC_SI", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.PhieuNhapThuoc", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_PHIEU_NHAP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"), 1L, 1);

                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<DateTime>("NgayLapPhieuNhap")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_LAP_PHIEU_NHAP");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TEN_NHA_CUNG_CAP");

                    b.Property<decimal>("TongTienNhap")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TONG_TIEN_NHAP");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex(new[] { "MaTk" }, "LAP_BOI_NHAN_VIEN_FK");

                    b.HasIndex(new[] { "MaPhieuNhap" }, "PHIEU_NHAP_THUOC_PK")
                        .IsUnique();

                    b.ToTable("PHIEU_NHAP_THUOC", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.PhieuThuTienThuoc", b =>
                {
                    b.Property<int>("MaPhieuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_PHIEU_THU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuThu"), 1L, 1);

                    b.Property<int>("MaDonThuoc")
                        .HasColumnType("int")
                        .HasColumnName("MA_DON_THUOC");

                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<DateTime>("NgayLapPhieuThu")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_LAP_PHIEU_THU");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TONG_TIEN");

                    b.HasKey("MaPhieuThu");

                    b.HasIndex(new[] { "MaDonThuoc" }, "CO_PHIEU_THU_FK");

                    b.HasIndex(new[] { "MaTk" }, "LAP_PHIEU_THU_FK");

                    b.HasIndex(new[] { "MaPhieuThu" }, "PHIEU_THU_TIEN_THUOC_PK")
                        .IsUnique();

                    b.ToTable("PHIEU_THU_TIEN_THUOC", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.PhuongPhapCanLamSang", b =>
                {
                    b.Property<int>("MaPhuongPhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_PHUONG_PHAP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongPhap"), 1L, 1);

                    b.Property<decimal>("ChiPhi")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("CHI_PHI");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("GHI_CHU");

                    b.Property<string>("TenPhuongPhap")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TEN_PHUONG_PHAP");

                    b.Property<string>("YeuCauDacBiet")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("YEU_CAU_DAC_BIET");

                    b.HasKey("MaPhuongPhap");

                    b.HasIndex(new[] { "MaPhuongPhap" }, "PHUONG_PHAP_CAN_LAM_SANG_PK")
                        .IsUnique();

                    b.ToTable("PHUONG_PHAP_CAN_LAM_SANG", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.QuyenTruyCap", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_QUYEN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"), 1L, 1);

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TEN_QUYEN");

                    b.HasKey("MaQuyen");

                    b.HasIndex(new[] { "MaQuyen" }, "QUYEN_TRUY_CAP_PK")
                        .IsUnique();

                    b.ToTable("QUYEN_TRUY_CAP", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.SuDungDichVu", b =>
                {
                    b.Property<int>("MaLanSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_LAN_SU_DUNG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLanSuDung"), 1L, 1);

                    b.Property<string>("DiaChiLienLac")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DIA_CHI_LIEN_LAC");

                    b.Property<int?>("HoaDonMaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnName("MA_DICH_VU");

                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<string>("MoTaBenhLy")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MO_TA_BENH_LY");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_BAT_DAU");

                    b.Property<string>("SoDienThoaiLienHe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SO_DIEN_THOAI_LIEN_HE")
                        .IsFixedLength();

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG");

                    b.Property<string>("TenNhanVienChiDinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TEN_NHAN_VIEN_CHI_DINH");

                    b.Property<short>("TrangThai")
                        .HasColumnType("smallint")
                        .HasColumnName("TRANG_THAI");

                    b.Property<short>("YeuCauChiDinhNhanVien")
                        .HasColumnType("smallint")
                        .HasColumnName("YEU_CAU_CHI_DINH_NHAN_VIEN");

                    b.HasKey("MaLanSuDung");

                    b.HasIndex("HoaDonMaHoaDon");

                    b.HasIndex(new[] { "MaDichVu" }, "CUA_DICH_VU_FK");

                    b.HasIndex(new[] { "MaTk" }, "SU_DUNG_DICH_VU_FK");

                    b.HasIndex(new[] { "MaLanSuDung" }, "SU_DUNG_DICH_VU_PK")
                        .IsUnique();

                    b.ToTable("SU_DUNG_DICH_VU", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTk"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("DIA_CHI");

                    b.Property<string>("DiaChiEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DIA_CHI_EMAIL");

                    b.Property<short>("GioiTinh")
                        .HasColumnType("smallint")
                        .HasColumnName("GIOI_TINH");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("HINH_ANH");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HO_TEN");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int")
                        .HasColumnName("MA_QUYEN");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("MAT_KHAU")
                        .IsFixedLength();

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAY_SINH");

                    b.Property<string>("SoCccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("char(12)")
                        .HasColumnName("SO_CCCD")
                        .IsFixedLength();

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("SO_DIEN_THOAI")
                        .IsFixedLength();

                    b.HasKey("MaTk");

                    b.HasIndex(new[] { "MaQuyen" }, "CO_QTC_FK");

                    b.HasIndex(new[] { "MaTk" }, "TAI_KHOAN_PK")
                        .IsUnique();

                    b.ToTable("TAI_KHOAN", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_THUOC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuoc"), 1L, 1);

                    b.Property<int>("HanSuDung")
                        .HasColumnType("int")
                        .HasColumnName("HAN_SU_DUNG");

                    b.Property<int>("MaDvt")
                        .HasColumnType("int")
                        .HasColumnName("MA_DVT");

                    b.Property<string>("MoTaThuoc")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("MO_TA_THUOC");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SO_LUONG");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TEN_THUOC");

                    b.HasKey("MaThuoc");

                    b.HasIndex(new[] { "MaDvt" }, "CO_DVT_FK");

                    b.HasIndex(new[] { "MaThuoc" }, "THUOC_PK")
                        .IsUnique();

                    b.ToTable("THUOC", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.TuVan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MA_TIN_NHAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"), 1L, 1);

                    b.Property<int>("BacMaTk")
                        .HasColumnType("int")
                        .HasColumnName("BAC_MA_TK");

                    b.Property<int>("MaTk")
                        .HasColumnType("int")
                        .HasColumnName("MA_TK");

                    b.Property<string>("NoiDungTinNhan")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("NOI_DUNG_TIN_NHAN");

                    b.Property<DateTime>("ThoiDiemNhanTin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("THOI_DIEM_NHAN_TIN");

                    b.Property<short>("TrangThaiTinNhan")
                        .HasColumnType("smallint")
                        .HasColumnName("TRANG_THAI_TIN_NHAN");

                    b.HasKey("MaTinNhan");

                    b.HasIndex(new[] { "BacMaTk" }, "TU_VAN_CHO_BENH_NHAN_FK");

                    b.HasIndex(new[] { "MaTinNhan" }, "TU_VAN_PK")
                        .IsUnique();

                    b.HasIndex(new[] { "MaTk" }, "YEU_CAU_TU_VAN_FK");

                    b.ToTable("TU_VAN", (string)null);
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.BacSi", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.ChuyenKhoa", "MaChuyenKhoaNavigation")
                        .WithMany("BacSis")
                        .HasForeignKey("MaChuyenKhoa")
                        .IsRequired()
                        .HasConstraintName("FK_BAC_SI_THUOC_CHU_CHUYEN_K");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.TaiKhoan", "MaTkNavigation")
                        .WithOne("BacSi")
                        .HasForeignKey("HTQL_DichVuYTeGiaDinh.Models.BacSi", "MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_BAC_SI_CO_TK2_TAI_KHOA");

                    b.Navigation("MaChuyenKhoaNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.BinhLuan", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.DichVuYTe", "MaDichVuNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaDichVu")
                        .IsRequired()
                        .HasConstraintName("FK_BINH_LUA_CO_BINH_L_DICH_VU_");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.KhachHang", "MaTkNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_BINH_LUA_VIET_BINH_KHACH_HA");

                    b.Navigation("MaDichVuNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChiTietDonThuoc", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.DonThuoc", "MaDonThuocNavigation")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaDonThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_CHI_TIET_CO_CHI_TI_DON_THUO");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_CHI_TIET_CO_THUOC_THUOC");

                    b.Navigation("MaDonThuocNavigation");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChiTietKetQuaCanLamSang", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.HoSoYTe", "MaHoSoNavigation")
                        .WithMany("ChiTietKetQuaCanLamSangs")
                        .HasForeignKey("MaHoSo")
                        .IsRequired()
                        .HasConstraintName("FK_CHI_TIET_CO_CHI_TI_HO_SO_Y_");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.PhuongPhapCanLamSang", "MaPhuongPhapNavigation")
                        .WithMany("ChiTietKetQuaCanLamSangs")
                        .HasForeignKey("MaPhuongPhap")
                        .IsRequired()
                        .HasConstraintName("FK_CHI_TIET_CUA_PHUON_PHUONG_P");

                    b.Navigation("MaHoSoNavigation");

                    b.Navigation("MaPhuongPhapNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.DichVuYTe", "MaDichVuNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CHI_TIET_KM_DV");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.ChuongTrinhKhuyenMai", "MaKhuyenMaiNavigation")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CHI_TIET_KM_CHO__KM");

                    b.Navigation("MaDichVuNavigation");

                    b.Navigation("MaKhuyenMaiNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.PhieuNhapThuoc", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .IsRequired()
                        .HasConstraintName("FK_CHI_TIET_NHAP_CHO__PHIEU_NH");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_CHI_TIET_NHAP_THUO_THUOC");

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DonGiaDichVu", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.DichVuYTe", "MaDichVuNavigation")
                        .WithMany("DonGiaDichVus")
                        .HasForeignKey("MaDichVu")
                        .IsRequired()
                        .HasConstraintName("FK_DON_GIA__CO_DON_GI_DICH_VU_");

                    b.Navigation("MaDichVuNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DonGiaThuoc", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("DonGiaThuocs")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_DON_GIA__CO_DON_GI_THUOC_");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DonThuoc", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.HoSoYTe", "MaHoSoNavigation")
                        .WithMany("DonThuocs")
                        .HasForeignKey("MaHoSo")
                        .IsRequired()
                        .HasConstraintName("FK_DON_THUO_CO_DON_TH_HO_SO_Y_");

                    b.Navigation("MaHoSoNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.HoaDon", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.SuDungDichVu", "MaLanSuDungNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaLanSuDung")
                        .IsRequired()
                        .HasConstraintName("FK_HOA_DON_CO_HOA_DO_SU_DUNG_");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.NhanVienYTe", "MaTkNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_HOA_DON_CO_NVYT_NHAN_VIE");

                    b.Navigation("MaLanSuDungNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.HoSoYTe", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.BacSi", "BacMaTkNavigation")
                        .WithMany("HoSoYTes")
                        .HasForeignKey("BacMaTk")
                        .IsRequired()
                        .HasConstraintName("FK_HO_SO_Y__GHI_HO_SO_BAC_SI");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.KhachHang", "MaTkNavigation")
                        .WithMany("HoSoYTes")
                        .HasForeignKey("MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_HO_SO_Y__CO_HO_SO__KHACH_HA");

                    b.Navigation("BacMaTkNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.KhachHang", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.HoGiaDinh", "MaHgdNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaHgd")
                        .IsRequired()
                        .HasConstraintName("FK_KHACH_HA_THUOC_HGD_HO_GIA_D");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.TaiKhoan", "MaTkNavigation")
                        .WithOne("KhachHang")
                        .HasForeignKey("HTQL_DichVuYTeGiaDinh.Models.KhachHang", "MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_KHACH_HA_CO_TK3_TAI_KHOA");

                    b.Navigation("MaHgdNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.NhanVienYTe", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.TaiKhoan", "MaTkNavigation")
                        .WithOne("NhanVienYTe")
                        .HasForeignKey("HTQL_DichVuYTeGiaDinh.Models.NhanVienYTe", "MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_NHAN_VIE_CO_TK_TAI_KHOA");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.PhanCongBacSi", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.HoGiaDinh", "MaHgdNavigation")
                        .WithMany("PhanCongBacSis")
                        .HasForeignKey("MaHgd")
                        .IsRequired()
                        .HasConstraintName("FK_PHAN_CON_CO_BAC_SI_HO_GIA_D");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.BacSi", "MaTkNavigation")
                        .WithMany("PhanCongBacSis")
                        .HasForeignKey("MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_PHAN_CON_PHAN_CONG_BAC_SI");

                    b.Navigation("MaHgdNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.PhieuNhapThuoc", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.NhanVienYTe", "MaTkNavigation")
                        .WithMany("PhieuNhapThuocs")
                        .HasForeignKey("MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEU_NH_LAP_BOI_N_NHAN_VIE");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.PhieuThuTienThuoc", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.DonThuoc", "MaDonThuocNavigation")
                        .WithMany("PhieuThuTienThuocs")
                        .HasForeignKey("MaDonThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEU_TH_CO_PHIEU__DON_THUO");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.NhanVienYTe", "MaTkNavigation")
                        .WithMany("PhieuThuTienThuocs")
                        .HasForeignKey("MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEU_TH_LAP_PHIEU_NHAN_VIE");

                    b.Navigation("MaDonThuocNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.SuDungDichVu", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.HoaDon", null)
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("HoaDonMaHoaDon");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.DichVuYTe", "MaDichVuNavigation")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDichVu")
                        .IsRequired()
                        .HasConstraintName("FK_SU_DUNG__CUA_DICH__DICH_VU_");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.KhachHang", "MaTkNavigation")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_SU_DUNG__SU_DUNG_D_KHACH_HA");

                    b.Navigation("MaDichVuNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.TaiKhoan", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.QuyenTruyCap", "MaQuyenNavigation")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaQuyen")
                        .IsRequired()
                        .HasConstraintName("FK_TAI_KHOA_CO_QTC_QUYEN_TR");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.Thuoc", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.DonViTinhThuoc", "MaDvtNavigation")
                        .WithMany("Thuocs")
                        .HasForeignKey("MaDvt")
                        .IsRequired()
                        .HasConstraintName("FK_THUOC_CO_DVT_DON_VI_T");

                    b.Navigation("MaDvtNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.TuVan", b =>
                {
                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.BacSi", "BacMaTkNavigation")
                        .WithMany("TuVans")
                        .HasForeignKey("BacMaTk")
                        .IsRequired()
                        .HasConstraintName("FK_TU_VAN_TU_VAN_CH_BAC_SI");

                    b.HasOne("HTQL_DichVuYTeGiaDinh.Models.KhachHang", "MaTkNavigation")
                        .WithMany("TuVans")
                        .HasForeignKey("MaTk")
                        .IsRequired()
                        .HasConstraintName("FK_TU_VAN_YEU_CAU_T_KHACH_HA");

                    b.Navigation("BacMaTkNavigation");

                    b.Navigation("MaTkNavigation");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.BacSi", b =>
                {
                    b.Navigation("HoSoYTes");

                    b.Navigation("PhanCongBacSis");

                    b.Navigation("TuVans");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChuongTrinhKhuyenMai", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.ChuyenKhoa", b =>
                {
                    b.Navigation("BacSis");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DichVuYTe", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("ChiTietKhuyenMais");

                    b.Navigation("DonGiaDichVus");

                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DonThuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");

                    b.Navigation("PhieuThuTienThuocs");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.DonViTinhThuoc", b =>
                {
                    b.Navigation("Thuocs");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.HoaDon", b =>
                {
                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.HoGiaDinh", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("PhanCongBacSis");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.HoSoYTe", b =>
                {
                    b.Navigation("ChiTietKetQuaCanLamSangs");

                    b.Navigation("DonThuocs");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.KhachHang", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("HoSoYTes");

                    b.Navigation("SuDungDichVus");

                    b.Navigation("TuVans");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.NhanVienYTe", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhieuNhapThuocs");

                    b.Navigation("PhieuThuTienThuocs");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.PhieuNhapThuoc", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.PhuongPhapCanLamSang", b =>
                {
                    b.Navigation("ChiTietKetQuaCanLamSangs");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.QuyenTruyCap", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.SuDungDichVu", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.TaiKhoan", b =>
                {
                    b.Navigation("BacSi");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVienYTe");
                });

            modelBuilder.Entity("HTQL_DichVuYTeGiaDinh.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");

                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("DonGiaThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
